FileVersion = 1

[Project]
Name = "ijoLang"
StartupObject = "ijoLang.Program"

[Configs.Debug.Win64]
DebugCommandArguments = "c $(ProjectDir)/examples/00_basics/00_hello_world.ijo"

[Configs."Debug - REPL".Win64]
BeefLibType = "Static"

[Configs."Debug - REPL".Win32]
BeefLibType = "Static"
