FileVersion = 1

[Project]
Name = "ijo"
StartupObject = "ijo.Program"
ProcessorMacros = ["DEBUG_TRACE_EXECUTION"]

[Configs.Debug.Win64]
DebugCommandArguments = "run $(ProjectDir)/examples/userFunction.ijo"

[Configs."Debug - REPL".Win64]
BeefLibType = "Static"

[Configs."Debug - REPL".Win32]
BeefLibType = "Static"
