FileVersion = 1

[Project]
Name = "ijoLang"
StartupObject = "ijoLang.Program"

[Configs.Debug.Win64]
DebugCommandArguments = "node $(ProjectDir)/examples/00_basics/01_basic_math.ijo"

[Configs."Debug - REPL".Win64]
BeefLibType = "Static"

[Configs."Debug - REPL".Win32]
BeefLibType = "Static"
