FileVersion = 1
Projects = {ijo = {Path = "Sources/ijo"}, "ijo.cli" = {Path = "Applications/ijo.cli"}, LybCL = {Path = "ThirdParty/LybCL"}}
WorkspaceFolders = {ThirdParty = ["LybCL"]}

[Workspace]
StartupProject = "ijo.cli"

[Configs.Test.Win32]
ConfigSelections = {corlib = {Config = "Debug"}}

[Configs.Test.Win64]
ConfigSelections = {corlib = {Config = "Debug"}}
