FileVersion = 1
Dependencies = {corlib = "*", ijo = "*"}

[Project]
Name = "ijo.cli"
StartupObject = "ijo.cli.Program"

[Configs.Debug.Win64]
DebugCommandArguments = "C:\\Users\\jonat\\Projects\\ijo\\Samples\\hello.ijo"

[Configs.Release.Win64]
BeefLibType = "Dynamic"
